@startgantt
Project starts 2022-10-01

[Research of Equations] starts 2022-10-01
[Research of Equations] ends 2022-10-31
[Research of Frontend] starts 2022-10-01
[Research of Frontend] ends 2022-10-31

@endgantt