@startgantt

'configure the gantt chart
printscale weekly zoom 2

'styles
<style>
ganttDiagram{
    task{
        FontSize 18
        Margin 10 0 0 0
        Padding 8
    }
    timeline{
        BackgroundColor Bisque
    }
    separator{
        BackgroundColor LightGray
        FontSize 18
    }
}
</style>

Project starts 2022-09-19

[BrainStorm Ideas] starts 2022-09-19 and ends 2022-09-26

[Examine other solutions] lasts 4 weeks

[Write Proposal] starts at 2022-09-26 and ends 2022-10-02

[Write Interim Report] starts at 2022-10-02 and ends 2022-12-09

-- Research --

[Research of the backend technologies] starts 2022-09-26 and ends 2022-11-06

[Research of the front-end Technologies] starts 2022-09-26 and ends 2022-11-06

[Research the Formula] starts at 2022-10-02 and ends 2022-10-25

[Research the Prayer times] starts at 2022-10-10 and ends 2022-11-06

[Research of the Quran] starts at 2022-10-20 and ends 2022-11-15

[Research the design methodologies] starts at 2022-10-25 and ends 2022-11-15

[Testing and Evaluation Plan] starts at 2022-11-15 and ends 2022-12-02

-- Prototype Development --
[Development Stage 1] starts at 2022-10-25 and ends 2022-12-09

[Develop Prototype 1] starts at 2022-10-25 and ends 2022-11-01
[Test Prototype 1] starts at 2022-11-01 and ends 2022-11-04

[Develop Prototype 2] starts at 2022-11-04 and ends 2022-11-20
[Test Prototype 2] starts at 2022-11-20 and ends 2022-11-25

[Develop Prototype 3] starts at 2022-11-25 and ends 2022-12-05
[Test Prototype 3] starts at 2022-12-05 and ends 2022-12-09

-- Final Report --
[Write Final Report] starts at 2022-12-09 and ends 2023-03-31

[Development Stage 2] starts at 2022-12-10 and ends 2023-03-01

[Testing and Evaluation] starts at 2023-03-01 and ends 2023-03-23

[Improvements] starts at 2023-03-23 and ends 2023-03-31

[Deployment] starts at 2023-03-31 and ends 2023-04-15

[Future Work] starts at 2023-04-15 and ends 2023-04-24

[Project Demo] starts 2023-04-24 and lasts 1 week

@endgantt