@startgantt

Project starts 2022-10-01

[Research of Equations] starts 2022-10-01
[Research of Equations] ends 2022-10-31

[Research of Prayer times in islam] starts 2022-10-10
[Research of Prayer times in islam] ends 2022-10-20

[Application Analysis] starts 2022-10-20
[Application Analysis] ends 2022-11-15

[Research of Frontend] starts 2022-10-31
[Research of Frontend] ends 2022-11-20

[Research of Backend] starts 2022-11-15
[Research of Backend] ends 2022-11-30

[Low fidelity Prototype] starts 2022-10-20
[Low fidelity Prototype] ends 2022-10-30

[Prototype 1] starts 2022-10-30 and ends 2022-11-22
[Test Prototype 1] starts at [Prototype 1]'s end
[Test Prototype 1] starts 2022-11-22 and ends 2022-11-30

[Research of Audio Analysis Solution] starts 2022-11-15
[Research of Audio Analysis Solution] ends 2022-12-20


'completion
[Research of Equations] is 100% complete
[Research of Prayer times in islam] is 100% complete
[Application Analysis] is 100% complete
[Research of Frontend] is 100% complete
[Research of Backend] is 100% complete
[Low fidelity Prototype] is 100% complete
[Prototype 1] is 100% complete
[Research of Audio Analysis Solution] is 10% complete

@endgantt