@startuml
'This digram summarises the layers of the application
skinparam componentStyle uml2
skinparam component {
  BackgroundColor FloralWhite
  BorderColor Black
  ArrowColor Crimson
}

'Layers
rectangle "Presentation Layer" as Presentation {

    frame "UI" as UI {
      [Component]
      note left
        The Components
        are the reusable
        UI elements
      end note

      [Component blogic]
      note right
        This is responsible for
        processing data
        and converting it into
        a useful format for the
        Component
      end note

      [Screen]
      note right
        This is responsible for
        displaying all the
        components
      end note

      [Activity]
      note right
        This is responsible for
        launching the UI
        and handling the
        navigation between
        screens
      end note
     }

     'activity calls screen
        [Activity] -down-> [Screen]
        [Screen] -down-> [Component]
        [Component] -right-> [Component blogic]


}

'business logic




@enduml