@startuml
rectangle "Frontend" as frontend{
[Android] as Android
}

rectangle location {
[Geocoder]
[Geolocation]
}

cloud {
rectangle "API" as backend {
    node "Nginx Service"{
        port 80 as HTTP
        port 443 as HTTPS
        rectangle {
            control "Reverse Proxy" as reverse_proxy
        }
    }

    node "Docker network" {
        frame "Backend Container" {
            port 3306 as mysql
            database "quran"
        }
        frame "Middle Tier Container"{
            port 8000 as nimaz_api_port
            [Spring Boot API] as Nimaz_API
        }
    }
  }
}


' external ports
    mysql -left-(3306
    HTTP -up-(80
    HTTPS -up-(443


    Android -down-> 80
    Android <-down-> 443
    Android <-right-> location

    reverse_proxy <-down-> nimaz_api_port

    Nimaz_API <-down-> mysql
@enduml