@startuml

enum CalculationMethod{
MUSLIM_WORLD_LEAGUE
EGYPTIAN
KARACHI
UMM_AL_QURA
DUBAI
MOON_SIGHTING_COMMITTEE
NORTH_AMERICA
KUWAIT
QATAR
SINGAPORE
FRANCE
RUSSIA
IRELAND
OTHER
+parameters: CalculationParameters
+getParameters(): CalculationParameters
+setParameters(parameters: CalculationParameters)
}

enum HighLatitudeRule{
MIDDLE_OF_THE_NIGHT
SEVENTH_OF_THE_NIGHT
TWILIGHT_ANGLE
}

enum madhab{
SHAFI
HANAFI
}

enum Prayer{
FAJR
SUNRISE
DHUHR
ASR
MAGHRIB
ISHA
NONE
}

enum ShadowLength{
+shadowLength: Double
SINGLE(1.0): Double
DOUBLE(2.0): Double
}
@enduml