@startuml PrayerTimes
class PrayerTimes {
- fajr : Date?
- sunrise: Date?
- dhuhr: Date?
- asr: Date?
- maghrib: Date?
- isha: Date?
- day: Int
- month: Int
- year: Int
- hour: Int
- minute: Int
- second: Int
+<<constructor>> PrayerTimes(coordinates, date, calculationParameters)
-<<instantiate>> calenderUtils : CalenderUtils()
+currentPrayer(time: Date): Prayer
+nextPrayer(time: Date): Prayer
+timeForPrayer(prayer: Prayer): Date
}
@enduml