@startuml
title "Manual Location"
'the user case diagram
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor FloralWhite
    BorderColor Black
    ArrowColor Black
}

actor "User" as user

rectangle {
    (Open App)

    (show prayer times)

    (get current Location)

    (get location from storage)
    (get location from GPS)
    (get location from Geocoder)

    (show timer for next prayer)

    (set alarm for each prayer)
    (show notification for each prayer)
    (Settings for each alarm)
    (Retrieve prayer times from server) as (2)


    'open app and show prayer times
    user -- (Open App)
    (Open App) -.> (show prayer times) : includes

    (show prayer times) -.> (get current Location) : includes
    (get current Location) <.- (get location from storage) : extends
    (get current Location) <.- (get location from GPS) : extends
    (get current Location) <.- (get location from Geocoder) : extends

    (show prayer times) -.> (show timer for next prayer) : includes
    (show prayer times) <.- (set alarm for each prayer) : extends
    (show prayer times) <.- (show notification for each prayer) : extends
    (show prayer times) <.- (Settings for each alarm) : extends
    (show prayer times) -.> (2) : includes
}
@enduml