@startuml
'https://plantuml.com/activity-diagram-beta
title Launch of the Application and Get prayer times
start
:Launch the application;
:Splash screen;
if (firstInstall?) then (true)
    :navigate to the introduction screen;
    :Show Welcome screen;
    :Show the Privacy Policy screen;
    :Show the Terms of Use screen;
    :Show the Set up screen;
    if(autoLocation?) then (true)
     :ask for location permission;
     if (permissionGranted?) then (yes)
     :find the location;
     :set the toggle button to true;
     else (no)
        :ask for location permission;
     endif
    else (false)
    :ask for location input;
    :Get coordinates from the input;
    endif
    :ask for Battery Optimization exemption;
    if (exempted?) then (yes)
    :send the intent to the android system;
    :set the toggle button to true;
    else (no)
    endif
else (false)
:navigate to the main screen;
:Call the Nimaz_api;
:Show loading Skeleton;
if(apiResponse?) then (yes)
    :show the prayer times;
else (no)
    :show the error message;
endif
:Show the Prayer Times;
endif
stop
@enduml
