@startuml
title Location permission logic

start
:User gets to the page;
if(Check if location permission is granted already) then (yes)
:permission granted;
else (no)
:Show manual location input by default;
:Show toggle button off;
endif
switch (on an event)
    case ()
            if(user toggle button?) then (on)
                :Request location permission;
                if(user grants permission) then (yes)
                    if(network is available) then (yes)
                        :Calculate prayer times;
                    else (no)
                        :Show error message toasts;
                    endif
                else (no)
                stop
                endif
            else (off)
                 :Show toast message;
                 :Navigate user to app settings;
                 stop
            endif

    case ()
            :user clicks manual location input;
            :Show manual location input dialog;
            if(user submits manual location input) then (yes)
                if(network is available) then (yes)
                    :Find coordinates of location;
                    :Calculate prayer times;
                else (no)
                    :Show error message toasts;
                    kill
                endif
            else (no)
                :User gets to the page;
                kill
            endif
    case ()
        :user moves away from page;
        :Show toast message;
        stop
endswitch
stop
'
'else (no)
'    if(user moves away from page) then (yes)
'        :Show toast message;
'    else (no)
'        :Show toast message;
'    endif
'endif

@enduml
