package com.arshadshah.nimaz.data.local.database.dao

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.arshadshah.nimaz.data.local.database.entity.ZakatHistoryEntity
import com.arshadshah.nimaz.data.local.user.NimazUserDatabase
import com.google.common.truth.Truth.assertThat
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * A record of what was calculated, and what was actually paid.
 *
 * `getTotalPaid` is a bare `SUM` with no `COALESCE`, so on an empty table it answers null rather
 * than zero — the caller has to know that, and this is where it is written down.
 */
@RunWith(RobolectricTestRunner::class)
class ZakatDaoTest {

    private lateinit var db: NimazUserDatabase
    private lateinit var dao: ZakatDao

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            NimazUserDatabase::class.java
        ).allowMainThreadQueries().build()
        dao = db.zakatDao()
    }

    @After
    fun tearDown() = db.close()

    @Test
    fun `calculations are listed newest first`() = runTest {
        dao.insertCalculation(calculation(calculatedAt = 100, zakatDue = 10.0))
        dao.insertCalculation(calculation(calculatedAt = 300, zakatDue = 30.0))
        dao.insertCalculation(calculation(calculatedAt = 200, zakatDue = 20.0))

        assertThat(dao.getAllHistory().first().map { it.calculatedAt })
            .containsExactly(300L, 200L, 100L).inOrder()
        assertThat(dao.getAllHistorySync().map { it.calculatedAt })
            .containsExactly(300L, 200L, 100L).inOrder()
    }

    @Test
    fun `two calculations at the same moment are both kept`() = runTest {
        // `insertCalculation` is a plain `@Insert` on an autogenerated key — nothing about a
        // repeat calculation makes it a replacement of the one before it.
        dao.insertCalculation(calculation(calculatedAt = 100, zakatDue = 10.0))
        dao.insertCalculation(calculation(calculatedAt = 100, zakatDue = 11.0))

        assertThat(dao.getAllHistorySync()).hasSize(2)
    }

    @Test
    fun `marking one calculation paid leaves the others owing`() = runTest {
        val first = dao.insertCalculation(calculation(calculatedAt = 100, zakatDue = 10.0))
        dao.insertCalculation(calculation(calculatedAt = 200, zakatDue = 20.0))

        dao.markAsPaid(first, paidAt = 555)

        val rows = dao.getAllHistorySync().associateBy { it.calculatedAt }
        assertThat(rows[100L]?.isPaid).isTrue()
        assertThat(rows[100L]?.paidAt).isEqualTo(555)
        assertThat(rows[200L]?.isPaid).isFalse()
        assertThat(rows[200L]?.paidAt).isNull()
    }

    @Test
    fun `the total paid sums only what was paid, and is null before anything is`() = runTest {
        assertThat(dao.getTotalPaid()).isNull()

        val first = dao.insertCalculation(calculation(calculatedAt = 100, zakatDue = 10.0))
        val second = dao.insertCalculation(calculation(calculatedAt = 200, zakatDue = 20.5))
        dao.insertCalculation(calculation(calculatedAt = 300, zakatDue = 99.0))
        dao.markAsPaid(first, paidAt = 555)
        dao.markAsPaid(second, paidAt = 666)

        assertThat(dao.getTotalPaid()).isEqualTo(30.5)
    }

    @Test
    fun `deleting one calculation removes only that one`() = runTest {
        val first = dao.insertCalculation(calculation(calculatedAt = 100, zakatDue = 10.0))
        dao.insertCalculation(calculation(calculatedAt = 200, zakatDue = 20.0))

        dao.deleteCalculation(first)

        assertThat(dao.getAllHistorySync().map { it.calculatedAt }).containsExactly(200L)
    }

    @Test
    fun `restoring a backup replaces the rows it carries ids for`() = runTest {
        dao.insertCalculations(
            listOf(
                calculation(id = 1, calculatedAt = 100, zakatDue = 10.0),
                calculation(id = 2, calculatedAt = 200, zakatDue = 20.0),
            )
        )
        dao.insertCalculations(listOf(calculation(id = 1, calculatedAt = 100, zakatDue = 12.0)))

        // The bulk insert is REPLACE so importing the same backup twice is idempotent.
        assertThat(dao.getAllHistorySync()).hasSize(2)
        assertThat(dao.getAllHistorySync().first { it.id == 1L }.zakatDue).isEqualTo(12.0)
    }

    @Test
    fun `deleting all user data empties the history`() = runTest {
        dao.insertCalculation(calculation(calculatedAt = 100, zakatDue = 10.0))

        dao.deleteAllUserData()

        assertThat(dao.getAllHistorySync()).isEmpty()
        assertThat(dao.getTotalPaid()).isNull()
    }

    private fun calculation(
        id: Long = 0,
        calculatedAt: Long,
        zakatDue: Double,
    ) = ZakatHistoryEntity(
        id = id,
        calculatedAt = calculatedAt,
        totalAssets = zakatDue * 40,
        totalLiabilities = 0.0,
        netWorth = zakatDue * 40,
        zakatDue = zakatDue,
        nisabType = "silver",
        nisabValue = 500.0,
        updatedAt = calculatedAt,
    )
}
