package com.arshadshah.nimaz.ui.theme
import androidx.compose.ui.graphics.Color

val raison_black_md_theme_light_primary = Color(0xFF6A4AB4)
val raison_black_md_theme_light_onPrimary = Color(0xFFFFFFFF)
val raison_black_md_theme_light_primaryContainer = Color(0xFFE9DDFF)
val raison_black_md_theme_light_onPrimaryContainer = Color(0xFF23005C)
val raison_black_md_theme_light_secondary = Color(0xFF8C4482)
val raison_black_md_theme_light_onSecondary = Color(0xFFFFFFFF)
val raison_black_md_theme_light_secondaryContainer = Color(0xFFFFD7F3)
val raison_black_md_theme_light_onSecondaryContainer = Color(0xFF390036)
val raison_black_md_theme_light_tertiary = Color(0xFF994719)
val raison_black_md_theme_light_onTertiary = Color(0xFFFFFFFF)
val raison_black_md_theme_light_tertiaryContainer = Color(0xFFFFDBCC)
val raison_black_md_theme_light_onTertiaryContainer = Color(0xFF351000)
val raison_black_md_theme_light_error = Color(0xFFBA1A1A)
val raison_black_md_theme_light_errorContainer = Color(0xFFFFDAD6)
val raison_black_md_theme_light_onError = Color(0xFFFFFFFF)
val raison_black_md_theme_light_onErrorContainer = Color(0xFF410002)
val raison_black_md_theme_light_background = Color(0xFFFFFBFF)
val raison_black_md_theme_light_onBackground = Color(0xFF1C1B1E)
val raison_black_md_theme_light_surface = Color(0xFFFFFBFF)
val raison_black_md_theme_light_onSurface = Color(0xFF1C1B1E)
val raison_black_md_theme_light_surfaceVariant = Color(0xFFE7E0EB)
val raison_black_md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val raison_black_md_theme_light_outline = Color(0xFF7A757F)
val raison_black_md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val raison_black_md_theme_light_inverseSurface = Color(0xFF323033)
val raison_black_md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val raison_black_md_theme_light_shadow = Color(0xFF000000)
val raison_black_md_theme_light_surfaceTint = Color(0xFF6A4AB4)
val raison_black_md_theme_light_outlineVariant = Color(0xFFCAC4CF)
val raison_black_md_theme_light_scrim = Color(0xFF000000)

val raison_black_md_theme_dark_primary = Color(0xFFD0BCFF)
val raison_black_md_theme_dark_onPrimary = Color(0xFF3A1283)
val raison_black_md_theme_dark_primaryContainer = Color(0xFF52309B)
val raison_black_md_theme_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val raison_black_md_theme_dark_secondary = Color(0xFFFFABEE)
val raison_black_md_theme_dark_onSecondary = Color(0xFF561250)
val raison_black_md_theme_dark_secondaryContainer = Color(0xFF702B69)
val raison_black_md_theme_dark_onSecondaryContainer = Color(0xFFFFD7F3)
val raison_black_md_theme_dark_tertiary = Color(0xFFFFB693)
val raison_black_md_theme_dark_onTertiary = Color(0xFF561F00)
val raison_black_md_theme_dark_tertiaryContainer = Color(0xFF7A3001)
val raison_black_md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCC)
val raison_black_md_theme_dark_error = Color(0xFFFFB4AB)
val raison_black_md_theme_dark_errorContainer = Color(0xFF93000A)
val raison_black_md_theme_dark_onError = Color(0xFF690005)
val raison_black_md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val raison_black_md_theme_dark_background = Color(0xFF1C1B1E)
val raison_black_md_theme_dark_onBackground = Color(0xFFE6E1E6)
val raison_black_md_theme_dark_surface = Color(0xFF1C1B1E)
val raison_black_md_theme_dark_onSurface = Color(0xFFE6E1E6)
val raison_black_md_theme_dark_surfaceVariant = Color(0xFF49454E)
val raison_black_md_theme_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val raison_black_md_theme_dark_outline = Color(0xFF948F99)
val raison_black_md_theme_dark_inverseOnSurface = Color(0xFF1C1B1E)
val raison_black_md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val raison_black_md_theme_dark_inversePrimary = Color(0xFF6A4AB4)
val raison_black_md_theme_dark_shadow = Color(0xFF000000)
val raison_black_md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val raison_black_md_theme_dark_outlineVariant = Color(0xFF49454E)
val raison_black_md_theme_dark_scrim = Color(0xFF000000)


val raison_black_md_seed = Color(0xFF492692)

