package com.arshadshah.nimaz.ui.theme
import androidx.compose.ui.graphics.Color

val Dark_Red_md_theme_light_primary = Color(0xFF9B4051)
val Dark_Red_md_theme_light_onPrimary = Color(0xFFFFFFFF)
val Dark_Red_md_theme_light_primaryContainer = Color(0xFFFFD9DD)
val Dark_Red_md_theme_light_onPrimaryContainer = Color(0xFF400012)
val Dark_Red_md_theme_light_secondary = Color(0xFF246C2D)
val Dark_Red_md_theme_light_onSecondary = Color(0xFFFFFFFF)
val Dark_Red_md_theme_light_secondaryContainer = Color(0xFFA8F5A5)
val Dark_Red_md_theme_light_onSecondaryContainer = Color(0xFF002105)
val Dark_Red_md_theme_light_tertiary = Color(0xFF7C5800)
val Dark_Red_md_theme_light_onTertiary = Color(0xFFFFFFFF)
val Dark_Red_md_theme_light_tertiaryContainer = Color(0xFFFFDEA7)
val Dark_Red_md_theme_light_onTertiaryContainer = Color(0xFF271900)
val Dark_Red_md_theme_light_error = Color(0xFFBA1A1A)
val Dark_Red_md_theme_light_errorContainer = Color(0xFFFFDAD6)
val Dark_Red_md_theme_light_onError = Color(0xFFFFFFFF)
val Dark_Red_md_theme_light_onErrorContainer = Color(0xFF410002)
val Dark_Red_md_theme_light_background = Color(0xFFFFFBFF)
val Dark_Red_md_theme_light_onBackground = Color(0xFF201A1B)
val Dark_Red_md_theme_light_surface = Color(0xFFFFFBFF)
val Dark_Red_md_theme_light_onSurface = Color(0xFF201A1B)
val Dark_Red_md_theme_light_surfaceVariant = Color(0xFFF4DDDF)
val Dark_Red_md_theme_light_onSurfaceVariant = Color(0xFF524344)
val Dark_Red_md_theme_light_outline = Color(0xFF847374)
val Dark_Red_md_theme_light_inverseOnSurface = Color(0xFFFBEEEE)
val Dark_Red_md_theme_light_inverseSurface = Color(0xFF362F2F)
val Dark_Red_md_theme_light_inversePrimary = Color(0xFFFFB2BC)
val Dark_Red_md_theme_light_shadow = Color(0xFF000000)
val Dark_Red_md_theme_light_surfaceTint = Color(0xFF9B4051)
val Dark_Red_md_theme_light_outlineVariant = Color(0xFFD7C1C3)
val Dark_Red_md_theme_light_scrim = Color(0xFF000000)

val Dark_Red_md_theme_dark_primary = Color(0xFFFFB2BC)
val Dark_Red_md_theme_dark_onPrimary = Color(0xFF5F1125)
val Dark_Red_md_theme_dark_primaryContainer = Color(0xFF7D293A)
val Dark_Red_md_theme_dark_onPrimaryContainer = Color(0xFFFFD9DD)
val Dark_Red_md_theme_dark_secondary = Color(0xFF8DD88B)
val Dark_Red_md_theme_dark_onSecondary = Color(0xFF00390D)
val Dark_Red_md_theme_dark_secondaryContainer = Color(0xFF005317)
val Dark_Red_md_theme_dark_onSecondaryContainer = Color(0xFFA8F5A5)
val Dark_Red_md_theme_dark_tertiary = Color(0xFFF7BD48)
val Dark_Red_md_theme_dark_onTertiary = Color(0xFF412D00)
val Dark_Red_md_theme_dark_tertiaryContainer = Color(0xFF5E4200)
val Dark_Red_md_theme_dark_onTertiaryContainer = Color(0xFFFFDEA7)
val Dark_Red_md_theme_dark_error = Color(0xFFFFB4AB)
val Dark_Red_md_theme_dark_errorContainer = Color(0xFF93000A)
val Dark_Red_md_theme_dark_onError = Color(0xFF690005)
val Dark_Red_md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val Dark_Red_md_theme_dark_background = Color(0xFF201A1B)
val Dark_Red_md_theme_dark_onBackground = Color(0xFFECE0E0)
val Dark_Red_md_theme_dark_surface = Color(0xFF201A1B)
val Dark_Red_md_theme_dark_onSurface = Color(0xFFECE0E0)
val Dark_Red_md_theme_dark_surfaceVariant = Color(0xFF524344)
val Dark_Red_md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C3)
val Dark_Red_md_theme_dark_outline = Color(0xFF9F8C8E)
val Dark_Red_md_theme_dark_inverseOnSurface = Color(0xFF201A1B)
val Dark_Red_md_theme_dark_inverseSurface = Color(0xFFECE0E0)
val Dark_Red_md_theme_dark_inversePrimary = Color(0xFF9B4051)
val Dark_Red_md_theme_dark_shadow = Color(0xFF000000)
val Dark_Red_md_theme_dark_surfaceTint = Color(0xFFFFB2BC)
val Dark_Red_md_theme_dark_outlineVariant = Color(0xFF524344)
val Dark_Red_md_theme_dark_scrim = Color(0xFF000000)


val Dark_Red_seed = Color(0xFF9B4051)