package com.arshadshah.nimaz.ui.theme

import androidx.compose.ui.graphics.Color

val raison_black_md_theme_light_primary = Color(0xFF744C9D)
val raison_black_md_theme_light_onPrimary = Color(0xFFFFFFFF)
val raison_black_md_theme_light_primaryContainer = Color(0xFFF0DBFF)
val raison_black_md_theme_light_onPrimaryContainer = Color(0xFF2C0051)
val raison_black_md_theme_light_secondary = Color(0xFF984718)
val raison_black_md_theme_light_onSecondary = Color(0xFFFFFFFF)
val raison_black_md_theme_light_secondaryContainer = Color(0xFFFFDBCC)
val raison_black_md_theme_light_onSecondaryContainer = Color(0xFF351000)
val raison_black_md_theme_light_tertiary = Color(0xFF984063)
val raison_black_md_theme_light_onTertiary = Color(0xFFFFFFFF)
val raison_black_md_theme_light_tertiaryContainer = Color(0xFFFFD9E3)
val raison_black_md_theme_light_onTertiaryContainer = Color(0xFF3E001F)
val raison_black_md_theme_light_error = Color(0xFFBA1A1A)
val raison_black_md_theme_light_errorContainer = Color(0xFFFFDAD6)
val raison_black_md_theme_light_onError = Color(0xFFFFFFFF)
val raison_black_md_theme_light_onErrorContainer = Color(0xFF410002)
val raison_black_md_theme_light_background = Color(0xFFFFFBFF)
val raison_black_md_theme_light_onBackground = Color(0xFF1D1B1E)
val raison_black_md_theme_light_surface = Color(0xFFFFFBFF)
val raison_black_md_theme_light_onSurface = Color(0xFF1D1B1E)
val raison_black_md_theme_light_surfaceVariant = Color(0xFFE9DFEB)
val raison_black_md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val raison_black_md_theme_light_outline = Color(0xFF7B757E)
val raison_black_md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val raison_black_md_theme_light_inverseSurface = Color(0xFF322F33)
val raison_black_md_theme_light_inversePrimary = Color(0xFFDCB8FF)
val raison_black_md_theme_light_shadow = Color(0xFF000000)
val raison_black_md_theme_light_surfaceTint = Color(0xFF744C9D)
val raison_black_md_theme_light_outlineVariant = Color(0xFFCCC4CE)
val raison_black_md_theme_light_scrim = Color(0xFF000000)

val raison_black_md_theme_dark_primary = Color(0xFFDCB8FF)
val raison_black_md_theme_dark_onPrimary = Color(0xFF431A6B)
val raison_black_md_theme_dark_primaryContainer = Color(0xFF5B3383)
val raison_black_md_theme_dark_onPrimaryContainer = Color(0xFFF0DBFF)
val raison_black_md_theme_dark_secondary = Color(0xFFFFB693)
val raison_black_md_theme_dark_onSecondary = Color(0xFF562000)
val raison_black_md_theme_dark_secondaryContainer = Color(0xFF7A3001)
val raison_black_md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCC)
val raison_black_md_theme_dark_tertiary = Color(0xFFFFB0CA)
val raison_black_md_theme_dark_onTertiary = Color(0xFF5D1135)
val raison_black_md_theme_dark_tertiaryContainer = Color(0xFF7A294B)
val raison_black_md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E3)
val raison_black_md_theme_dark_error = Color(0xFFFFB4AB)
val raison_black_md_theme_dark_errorContainer = Color(0xFF93000A)
val raison_black_md_theme_dark_onError = Color(0xFF690005)
val raison_black_md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val raison_black_md_theme_dark_background = Color(0xFF1D1B1E)
val raison_black_md_theme_dark_onBackground = Color(0xFFE7E1E5)
val raison_black_md_theme_dark_surface = Color(0xFF1D1B1E)
val raison_black_md_theme_dark_onSurface = Color(0xFFE7E1E5)
val raison_black_md_theme_dark_surfaceVariant = Color(0xFF4A454E)
val raison_black_md_theme_dark_onSurfaceVariant = Color(0xFFCCC4CE)
val raison_black_md_theme_dark_outline = Color(0xFF968E98)
val raison_black_md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val raison_black_md_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val raison_black_md_theme_dark_inversePrimary = Color(0xFF744C9D)
val raison_black_md_theme_dark_shadow = Color(0xFF000000)
val raison_black_md_theme_dark_surfaceTint = Color(0xFFDCB8FF)
val raison_black_md_theme_dark_outlineVariant = Color(0xFF4A454E)
val raison_black_md_theme_dark_scrim = Color(0xFF000000)


val raison_black_seed = Color(0xFF443454)
