package com.arshadshah.nimaz.core.util

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.LinearGradient
import android.graphics.Paint
import android.graphics.Shader
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import androidx.core.content.res.ResourcesCompat
import androidx.core.graphics.withTranslation
import com.arshadshah.nimaz.core.ui.R
import com.arshadshah.nimaz.core.common.formatMediumDate
import com.arshadshah.nimaz.core.monitoring.CrashReporter
import com.arshadshah.nimaz.domain.model.Ayah
import com.arshadshah.nimaz.domain.model.TafseerHighlight
import java.io.File
import java.io.FileOutputStream
import java.time.LocalDate

private val TEAL = 0xFF14B8A6.toInt()
private val TEAL_DARK = 0xFF0F766E.toInt()
private val INK = 0xFF1C1917.toInt()
private val MUTED = 0xFF78716C.toInt()
private val LINE = 0xFFE7E5E4.toInt()
private val GOLD = 0xFFEAB308.toInt()

private const val PAGE_W = 595
private const val PAGE_H = 842
private const val MARGIN = 40f
private const val HEADER_H = 96f
private const val CONTENT_TOP = HEADER_H + 26f
private const val FOOTER_Y = PAGE_H - 40f
private const val CONTENT_BOTTOM = FOOTER_Y - 14f

/**
 * Exports a single ayah's tafseer to a branded, **print- and share-ready** PDF.
 *
 * Layout: a teal gradient header carrying the app monogram, the surah name and
 * the ayah/source on the right; then the Arabic ayah (Amiri, centred), the
 * translation, the commentary itself, and finally the user's own highlight
 * notes. Long commentary flows across as many A4 pages as needed — each with the
 * same branded header and a "Generated by Nimaz · date · page" footer.
 *
 * Mirrors [PrayerTimesPdfExporter]'s conventions (fonts, `exports/` cache dir) so
 * both share the same visual language. Produces only the [File]; sharing goes
 * through `ContentShareManager.shareFile(...)`. All user-facing labels are
 * resolved from resources, so the PDF respects the app language.
 */
object TafseerPdfExporter {

    fun export(
        context: Context,
        surahName: String,
        ayah: Ayah,
        sourceLabel: String,
        tafseerText: String,
        highlights: List<TafseerHighlight>,
    ): File {
        val body =
            ResourcesCompat.getFont(context, R.font.plus_jakarta_sans_variable) ?: Typeface.DEFAULT
        val heading = ResourcesCompat.getFont(context, R.font.outfit_variable) ?: Typeface.DEFAULT
        val arabicFont = ResourcesCompat.getFont(context, R.font.amiri_regular) ?: Typeface.SERIF
        val bold = Typeface.create(heading, Typeface.BOLD)

        val contentWidth = (PAGE_W - 2 * MARGIN).toInt()

        val doc = PdfDocument()
        val writer = PageWriter(
            doc = doc,
            context = context,
            body = body,
            bold = bold,
            surahName = surahName,
            ayahNumber = ayah.ayahNumber,
            sourceLabel = sourceLabel
        )
        writer.beginDocument()

        // Arabic ayah — centred.
        val arabicPaint = TextPaint().apply {
            isAntiAlias = true; color = INK; typeface = arabicFont; textSize = 22f
        }
        writer.flow(
            layout(ayah.textArabic, arabicPaint, contentWidth, Layout.Alignment.ALIGN_CENTER, 6f),
            spacingBefore = 2f,
            spacingAfter = 14f
        )
        writer.divider()

        // Translation.
        val translation = ayah.translation
        if (!translation.isNullOrBlank()) {
            writer.label(context.getString(R.string.translation))
            val tp = TextPaint().apply {
                isAntiAlias = true; color = INK; typeface = body; textSize = 11.5f
            }
            writer.flow(
                layout(translation, tp, contentWidth, Layout.Alignment.ALIGN_NORMAL, 3f),
                spacingAfter = 14f
            )
            writer.divider()
        }

        // Commentary.
        writer.label(context.getString(R.string.tafseer_pdf_commentary) + "  ·  " + sourceLabel)
        val commentaryPaint = TextPaint().apply {
            isAntiAlias = true; color = INK; typeface = body; textSize = 11.5f
        }
        writer.flow(
            layout(tafseerText, commentaryPaint, contentWidth, Layout.Alignment.ALIGN_NORMAL, 4f),
            spacingAfter = 8f
        )

        // The user's own highlight notes.
        val withNotes = highlights.filter { !it.note.isNullOrBlank() }
        if (withNotes.isNotEmpty()) {
            writer.space(10f)
            writer.divider()
            writer.label(context.getString(R.string.tafseer_pdf_notes))
            val snippetPaint = TextPaint().apply {
                isAntiAlias = true; color = MUTED
                typeface = Typeface.create(body, Typeface.ITALIC); textSize = 10f
            }
            val notePaint = TextPaint().apply {
                isAntiAlias = true; color = INK; typeface = body; textSize = 11f
            }
            withNotes.forEach { highlight ->
                val s = highlight.startOffset.coerceIn(0, tafseerText.length)
                val e = highlight.endOffset.coerceIn(s, tafseerText.length)
                val snippet = if (s < e) tafseerText.substring(s, e) else ""
                val accent = parseHex(highlight.color)
                if (snippet.isNotBlank()) {
                    val shown = if (snippet.length > 160) snippet.take(160) + "…" else snippet
                    writer.flow(
                        layout(
                            "“$shown”",
                            snippetPaint,
                            contentWidth - 14,
                            Layout.Alignment.ALIGN_NORMAL,
                            2f
                        ),
                        spacingBefore = 8f,
                        spacingAfter = 3f,
                        accentColor = accent,
                        indent = 14f
                    )
                }
                writer.flow(
                    layout(
                        highlight.note.orEmpty(),
                        notePaint,
                        contentWidth - 14,
                        Layout.Alignment.ALIGN_NORMAL,
                        2f
                    ),
                    spacingAfter = 4f,
                    indent = 14f
                )
            }
        }

        writer.endDocument()

        val dir = File(context.cacheDir, "exports").apply { mkdirs() }
        val safeSurah = surahName.replace(Regex("[^A-Za-z0-9]+"), "_").trim('_').ifBlank { "Surah" }
        val file = File(dir, "Nimaz_Tafseer_${safeSurah}_${ayah.ayahNumber}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()
        return file
    }
}

/**
 * Drives the multi-page layout: owns the current page/canvas and the running
 * `y` cursor, paints the branded header/footer on every page, and flows
 * [StaticLayout] blocks line-by-line so a block that overruns the page continues
 * cleanly on the next one.
 */
private class PageWriter(
    private val doc: PdfDocument,
    private val context: Context,
    private val body: Typeface,
    private val bold: Typeface,
    private val surahName: String,
    private val ayahNumber: Int,
    private val sourceLabel: String,
) {
    private var page: PdfDocument.Page? = null
    private var canvas: Canvas? = null
    private var y = 0f
    private var pageNum = 0

    fun beginDocument() = newPage()

    fun endDocument() {
        page?.let { drawFooter(it.canvas); doc.finishPage(it) }
        page = null
        canvas = null
    }

    private fun newPage() {
        page?.let { drawFooter(it.canvas); doc.finishPage(it) }
        pageNum++
        val p = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, pageNum).create())
        page = p
        canvas = p.canvas
        drawHeader(p.canvas)
        y = CONTENT_TOP
    }

    /** A small teal section label (e.g. "Commentary", "Translation"). */
    fun label(text: String) {
        if (y + 20f > CONTENT_BOTTOM) newPage()
        val p = Paint().apply {
            isAntiAlias = true; color = TEAL_DARK
            typeface = Typeface.create(body, Typeface.BOLD); textSize = 9.5f
        }
        canvas!!.drawText(text, MARGIN, y + 10f, p)
        y += 20f
    }

    fun divider() {
        if (y + 12f > CONTENT_BOTTOM) newPage()
        canvas!!.drawLine(
            MARGIN, y, PAGE_W - MARGIN, y,
            Paint().apply { color = LINE; strokeWidth = 0.8f }
        )
        y += 12f
    }

    fun space(h: Float) {
        if (y + h > CONTENT_BOTTOM) newPage() else y += h
    }

    /**
     * Render [block], breaking it across pages at line boundaries. [indent]
     * shifts the text right (used for the accented note snippets); [accentColor],
     * when set, paints a thin coloured rule down the left of the block.
     */
    fun flow(
        block: StaticLayout,
        spacingBefore: Float = 0f,
        spacingAfter: Float = 0f,
        accentColor: Int? = null,
        indent: Float = 0f,
    ) {
        y += spacingBefore
        var line = 0
        while (line < block.lineCount) {
            val baseTop = block.getLineTop(line)
            val avail = CONTENT_BOTTOM - y
            var end = line
            while (end < block.lineCount && (block.getLineBottom(end) - baseTop) <= avail) end++
            if (end == line) {
                // Not even one line fits in the remaining space — advance a page.
                newPage()
                continue
            }
            val sliceTop = block.getLineTop(line)
            val sliceBottom = block.getLineBottom(end - 1)
            val height = (sliceBottom - sliceTop).toFloat()
            val c = canvas!!

            if (accentColor != null) {
                c.drawRect(
                    MARGIN, y, MARGIN + 3f, y + height,
                    Paint().apply {
                        isAntiAlias = true; color = accentColor; style = Paint.Style.FILL
                    }
                )
            }

            c.withTranslation(MARGIN + indent, y - sliceTop) {
                clipRect(0f, sliceTop.toFloat(), PAGE_W.toFloat(), sliceBottom.toFloat())
                block.draw(this)
            }

            y += height
            line = end
        }
        y += spacingAfter
    }

    private fun drawHeader(c: Canvas) {
        c.drawRect(
            0f, 0f, PAGE_W.toFloat(), HEADER_H,
            Paint().apply {
                isAntiAlias = true
                shader = LinearGradient(
                    0f, 0f, PAGE_W.toFloat(), 0f, TEAL, TEAL_DARK, Shader.TileMode.CLAMP
                )
            }
        )
        // App logo in a white tile.
        val tile = 42f
        c.drawRoundRect(MARGIN, 27f, MARGIN + tile, 27f + tile, 11f, 11f, fill(Color.WHITE))
        runCatching {
            val logo = context.packageManager.getApplicationIcon(context.packageName)
            val pad = 5
            logo.setBounds(
                (MARGIN + pad).toInt(), 27 + pad,
                (MARGIN + tile - pad).toInt(), (27 + tile - pad).toInt()
            )
            logo.draw(c)
        }.onFailure { CrashReporter.recordException(it) }

        val title = Paint().apply {
            isAntiAlias = true; color = Color.WHITE; typeface = bold; textSize = 25f
        }
        c.drawText("Nimaz", MARGIN + 52f, 44f, title)
        val eyebrow = Paint().apply {
            isAntiAlias = true; color = 0xCCFFFFFF.toInt(); typeface = body; textSize = 11f
        }
        c.drawText(context.getString(R.string.tafseer_pdf_header), MARGIN + 53f, 64f, eyebrow)

        val rTitle = Paint().apply {
            isAntiAlias = true; color = Color.WHITE; typeface = bold; textSize = 17f
            textAlign = Paint.Align.RIGHT
        }
        c.drawText(surahName, PAGE_W - MARGIN, 42f, rTitle)
        val rSub = Paint().apply {
            isAntiAlias = true; color = 0xCCFFFFFF.toInt(); typeface = body; textSize = 11f
            textAlign = Paint.Align.RIGHT
        }
        c.drawText(
            context.getString(R.string.tafseer_pdf_ayah, ayahNumber) + "  ·  " + sourceLabel,
            PAGE_W - MARGIN, 60f, rSub
        )
    }

    private fun drawFooter(c: Canvas) {
        c.drawLine(
            MARGIN, FOOTER_Y, PAGE_W - MARGIN, FOOTER_Y,
            Paint().apply { color = TEAL; strokeWidth = 1.2f }
        )
        val date = LocalDate.now().formatMediumDate()
        val ft = Paint().apply {
            isAntiAlias = true; color = MUTED; typeface = body; textSize = 9f
        }
        c.drawText(
            context.getString(R.string.tafseer_pdf_footer) + "  ·  " + date,
            MARGIN, FOOTER_Y + 14f, ft
        )
        ft.textAlign = Paint.Align.RIGHT
        c.drawText(pageNum.toString(), PAGE_W - MARGIN, FOOTER_Y + 14f, ft)
    }
}

// ── helpers ────────────────────────────────────────────────────────────────

private fun layout(
    text: String,
    paint: TextPaint,
    width: Int,
    align: Layout.Alignment,
    lineSpacingExtra: Float = 0f,
): StaticLayout =
    StaticLayout.Builder
        .obtain(text, 0, text.length, paint, width.coerceAtLeast(1))
        .setAlignment(align)
        .setLineSpacing(lineSpacingExtra, 1f)
        .setIncludePad(false)
        .build()

private fun fill(color: Int) =
    Paint().apply { isAntiAlias = true; this.color = color; style = Paint.Style.FILL }

private fun parseHex(hex: String): Int = runCatching {
    val clean = hex.removePrefix("#")
    when (clean.length) {
        6 -> (0xFF000000.toInt()) or clean.toLong(16).toInt()
        8 -> clean.toLong(16).toInt()
        else -> GOLD
    }
}.getOrDefault(GOLD)
