package com.arshadshah.nimaz.domain.search

import java.text.Normalizer

/**
 * Folds what someone types and what the corpus stores onto the same string (#330).
 *
 * Arabic search returned **zero results for every query**, always, for as long as the
 * app has had a search box. `SELECT … WHERE text_arabic LIKE '%الله%'` matched nothing
 * and الله is in 1,746 verses. Nobody reported it, because an empty result list reads
 * as "no results" rather than as "this cannot ever work".
 *
 * Two causes stack, and neither is fixable with a smarter `LIKE`:
 *
 *  1. **Combining marks.** The stored text is fully vocalised. `ٱلرَّحْمَٰنِ` is twelve
 *     codepoints — shadda, fatha, sukun, superscript alef, kasra — and a keyboard
 *     produces six. No substring of the stored value equals what anyone types.
 *  2. **Alef Wasla.** The first letter of 77% of ayahs is U+0671 (ٱ), a different
 *     *letter* from U+0627 (ا), so stripping diacritics does not fix it on its own.
 *
 * ## This is one half of a folding, and the other half is in another repository
 *
 * The shipped `search_index` stores each body folded, by
 * `nimaz_data/normalise/arabic.py` in arshad-shah/nimaz-data. A query has to be folded
 * *identically* or it matches nothing — and a folding that disagrees with itself fails
 * exactly the way no folding at all does: silently, with an empty list.
 *
 * So the agreement is a committed file rather than a promise.
 * `app/src/test/resources/search/fold-fixtures.json` is generated by
 * `nz search fixtures`, exported here by `nz app sync`, and
 * `ArabicSearchNormaliserTest` asserts this implementation reproduces every pair in
 * it. Changing anything below without regenerating that file fails the build on both
 * sides, which is the point.
 *
 * [FOLD_VERSION] is stamped into the artifact's `search_meta`; a reader that finds a
 * different number refuses the index rather than quietly under-matching.
 */
object ArabicSearchNormaliser {

    /** Bumped when the folding changes. Must equal `search_meta.fold_version`. */
    const val FOLD_VERSION = 1

    /**
     * The form in which two spellings of the same word are one string.
     *
     * Idempotent, so it is safe to fold something already folded.
     */
    fun fold(text: String?): String {
        if (text.isNullOrEmpty()) return ""
        val decomposed = Normalizer.normalize(text, Normalizer.Form.NFD)
        val out = StringBuilder(decomposed.length)
        var pendingSpace = false
        for (char in decomposed) {
            if (isDropped(char)) continue
            // `isSpaceChar` as well as `isWhitespace`, because Java calls U+00A0 one and
            // not the other while Python's `\s` matches both — and the two sides of this
            // folding have to agree about what a space is.
            if (char.isWhitespace() || Character.isSpaceChar(char)) {
                // Collapsed rather than kept: the data side collapses runs of whitespace
                // to one space and trims, and "identically" has to mean identically.
                if (out.isNotEmpty()) pendingSpace = true
                continue
            }
            if (pendingSpace) {
                out.append(' ')
                pendingSpace = false
            }
            out.append(LETTERS[char] ?: DIGITS[char] ?: char)
        }
        // `lowercase()`, which is locale-independent — not `toLowerCase(default locale)`,
        // which turns I into ı on a Turkish phone and would fold a query differently
        // there than the index was built.
        return out.toString().lowercase()
    }

    /**
     * The folded words of [text], split the way SQLite's `unicode61` tokenizer split the
     * indexed text: letters and digits are part of a word, everything else separates two.
     *
     * A character scan rather than a regex, so that this and the Python side agree by
     * construction instead of by two regex dialects happening to match.
     */
    fun tokens(text: String?): List<String> {
        val folded = fold(text)
        if (folded.isEmpty()) return emptyList()
        val out = mutableListOf<String>()
        val current = StringBuilder()
        for (char in folded) {
            if (char.isLetterOrDigit()) {
                current.append(char)
            } else if (current.isNotEmpty()) {
                out.add(current.toString())
                current.clear()
            }
        }
        if (current.isNotEmpty()) out.add(current.toString())
        return out
    }

    /**
     * The query as an FTS MATCH expression, keeping the ranking above it meaningful.
     *
     * `SearchLibraryUseCase` searches the whole phrase (scored 100) *and* each
     * significant word (scored 1), then merges — so a verse matching the whole phrase
     * outranks one that matched two of its words. That only works if the two passes ask
     * different questions, which is what this does:
     *
     *  - **one word** → `word*`, a prefix term. There is no stemmer here, and the prefix
     *    is what lets `rahman` reach the transliterated `ar-rahmani` and what makes a
     *    half-typed word behave the way a search box is expected to.
     *  - **several words** → `"a b c"`, an FTS phrase: those words, adjacent, in that
     *    order. This is the same question `LIKE '%a b c%'` asked and the reason the
     *    phrase bonus means anything. OR-ing the terms here instead would give every
     *    single-word hit the phrase score and flatten the ranking to noise.
     *
     * Returns "" when the query has no searchable content; callers must treat that as
     * "no query" rather than passing it to `MATCH`, which throws on an empty expression.
     */
    fun matchExpression(query: String?): String {
        val terms = tokens(query)
        return when (terms.size) {
            0 -> ""
            1 -> "${terms[0]}*"
            else -> terms.joinToString(separator = " ", prefix = "\"", postfix = "\"")
        }
    }

    // --- the folding table ----------------------------------------------------------
    //
    // Mirrors nimaz_data/normalise/arabic.py. Ranges are inclusive.

    private fun isDropped(char: Char): Boolean = when (char.code) {
        // Zero-width and bidi controls: typography, never a distinction between words.
        in 0x200B..0x200F, in 0x202A..0x202E, in 0x2066..0x2069, 0x061C, 0xFEFF -> true
        // Private use. The IndoPak editions end every verse with a font-specific glyph
        // that is not a letter in any script.
        in 0xE000..0xF8FF -> true
        // Combining marks: Latin/Greek/Cyrillic after NFD, and the Arabic ones, which
        // are written as their own codepoints and never arrive by decomposition.
        in 0x0300..0x036F -> true
        in 0x0610..0x061A -> true
        in 0x064B..0x065F -> true
        0x0670 -> true
        in 0x06D6..0x06ED -> true
        in 0x08D3..0x08FF -> true
        // Tatweel stretches the baseline; the standalone hamza is spelled both ways
        // (ماء / ما) often enough that keeping it costs more matches than it saves.
        0x0640, 0x0621 -> true
        else -> false
    }

    private val LETTERS: Map<Char, Char> = mapOf(
        // every alef form -> bare alef
        'آ' to 'ا',  // آ  alef with madda
        'أ' to 'ا',  // أ  alef with hamza above
        'إ' to 'ا',  // إ  alef with hamza below
        'ٱ' to 'ا',  // ٱ  alef wasla — 77% of ayahs, and not a diacritic
        'ٲ' to 'ا',
        'ٳ' to 'ا',
        'ٵ' to 'ا',
        'ى' to 'ي',  // ى  alef maqsura -> ya
        'ة' to 'ه',  // ة  ta marbuta   -> ha
        'ؤ' to 'و',  // ؤ  hamza on waw -> waw
        'ئ' to 'ي',  // ئ  hamza on ya  -> ya
        // Persian/Urdu letterforms -> their Arabic counterparts. The corpus carries two
        // Urdu translations, and Urdu ی (U+06CC) is not the ي anyone typing Arabic uses.
        'ک' to 'ك',  // ک -> ك
        'ڪ' to 'ك',
        'ی' to 'ي',  // ی -> ي
        'ے' to 'ي',  // ے -> ي
        'ۓ' to 'ي',
        'ہ' to 'ه',  // ہ -> ه
        'ۃ' to 'ه',
        'ھ' to 'ه',  // ھ -> ه
        'ں' to 'ن',  // ں -> ن
    )

    private val DIGITS: Map<Char, Char> = buildMap {
        for (n in 0..9) {
            put('٠' + n, '0' + n)  // Arabic-Indic
            put('۰' + n, '0' + n)  // extended Arabic-Indic
        }
    }
}
